# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 755870f593ee5b54a348bfe40181f99c3d3b49e10f5c76832a9114fadf55da84a3341c2def483031eb1b84f38077a4dd7c9f3e5b2c47f2ba45b2113adfabde19

test:
  secret_key_base: 1f4b435f83d2077716bbacdb1f044775e79324e39a5cf33f2706cca5f3266232863c2dcec55afb10c8ba14d0758809b05d9f364dc626d0fbca5aaa0dee2e1940

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
